language: python
python: 2.7
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U setuptools pip
- pip install -U platformio
- platformio platforms install espressif8266 --with-package tool-mkspiffs
script:
- platformio run -e esp12e
- ~/.platformio/packages/tool-mkspiffs/mkspiffs -c data -p 256 -b 8192 -s 1028096 .pioenvs/esp12e/spiffs.bin